### ISSUE TITLE
Двумерные массивы

### ISSUE THREAD

**Issue by casa7x** [xydoy92/lesson_14#1]
https://github.com/xydoy92/lesson_14/blob/1be237a591a1bce955ecd3ae9717acd303996a43/script.js#L12

Давай не будем усложнять себе жизнь. Разбей на отдельные массивы всё   и работай через них. Заведи ещё 2 перменные и если больше 18 лет, добавляй в массив со взрослыми, если меньше, то в массив с детьми, не надо так себе усложнять. Ты же можешь обращаться к свойству напрямую, не через [] скобки. persons[i].age к примеру. Удобнее читать такое. Ну и ты всё в одном массиве сделал опять таки, в задаче было написано - разделить )

**Comment by xydoy92** [comment]
Разбил на отдельные массивы и сделал всё через них. По поводу квадратных скобок: поскольку они дают больше возможностей, то я себя приучаю писать через них, а не через точку. И мне не кажется, что это неудобно читать.

**Comment by casa7x** [comment]
Тебе не кажется, потому-что у тебя несколько строк кода. 
Квадратные скобки не дают больше возможностей, они позволяют делать свойство вычисляемым, передавая туда перменные. А запись через ["profession"] и .profession, так вообще ничем не отличается по возможностям, кроме того, что ты добавляешь скобки и кавычки)  И с точки зрения чистоты кода, второй вариант очевидно, читабельнее. Если ты напрямую можешь обратиться к свойству, не вижу причин этого не делать, а скобки тебе просто добавляют опций, которыми ты можешь воспользоваться, когда нужно. Ты в большинстве случае, будешь видеть обращение через точку, чем через квадратные скобки. Поэтому приучивать себя к лишнему не надо

Чтобы ты понимал, это не значит, что ты неправильно сделал. Я тебе объясняю, что это лишнее. Плюс когда ты будешь работать в IDE, тебе сложнее будет искать его, подсказок и переходов по свойству не будет. Плюс если вдруг затеишь рефакторинг, то надо будет в ногу стрелять)
