### ISSUE TITLE
Проверка на null

### ISSUE THREAD

**Issue by casa7x** [xydoy92/lesson_14#2]
https://github.com/xydoy92/lesson_14/blob/1be237a591a1bce955ecd3ae9717acd303996a43/valid_without_functions.js#L23

В какаих случаях у тебя логин и тоже самое с паролем, могут быть null ? У тебя также есть проверка отдельная на пустую строку. Не проще ли здесь все ложные значения обработать просто и написать !login  ?

**Comment by xydoy92** [comment]
Нет, эта проверка нужна. Когда пользователь жмёт отмену или escape при любом вводе, я хочу дать ему возможность уйти. А если он просто ничего не ввёл, пусть вводит опять, вдруг он случайно ОК сразу нажал?
