### ISSUE TITLE
Что этот код делает?

### ISSUE THREAD

**Issue by casa7x** [xydoy92/lesson_14#3]
https://github.com/xydoy92/lesson_14/blob/1be237a591a1bce955ecd3ae9717acd303996a43/valid_without_functions.js#L86

Не очень понимаю за что этот код отвечает весь? Дублирует практически весь предыдущий.
Если это уже непосредственный вход пользователя, то зачем его пре-валидировать, там же может быть только 3 варианта только - "Такого пользователя нет", "неверный пароль", "Успешный вход"

**Comment by xydoy92** [comment]
Убрал превалидации и ненужные проверки при входе.
