### ISSUE TITLE
Нэйминг

### ISSUE THREAD

**Issue by casa7x** [xydoy92/lesson_14#4]
https://github.com/xydoy92/lesson_14/blob/3abdb2e85bab3e56c70d55c46b51cccddb1b3855/script.js#L10

adult = взрослый, у тебя как минммум массив, либо уже множественное число поставь, а ещё лучше в таком лсучае указать как adultList

notAdult - крайне расплывчатое понятие, плюс опять таки единственное число, я думаю здесь можно более прямо указать, что тут дети

**Comment by xydoy92** [comment]
Переделал нэйминг. Всё время забываю про волшебное слово List!((
Сделал через точки вместо квадратных скобок, хотя больше доверялся твоему опыту и настойчивости, чем сам понял, что так лучше. Возможно, понимание придёт позже.
